# Build file for OOMAnalyser
#
# Copyright (c) 2020-2024 Carsten Grohmann
# License: MIT (see LICENSE.txt)
# THIS PROGRAM COMES WITH NO WARRANTY

image: archlinux
arch:  x86_64
packages:
  - python3
  - python-black
  - python-virtualenv
  - git
  - xorg-server-xvfb
sources:
  - https://git.sr.ht/~carstengrohmann/OOMAnalyser
shell: null
tasks:
  - setup_pkgs: |
      # Use precompiled Python binaries to speedup test from 17 minutes to 12 minutes
      cat << EOT | sudo bash -
      echo "[python]" >> /etc/pacman.conf
      echo "SigLevel = Optional" >> /etc/pacman.conf
      echo "Server = https://ffy00.github.io/arch-python-repo/" >> /etc/pacman.conf
      EOT
      # install pre-compiled Python 3.7 incl. dependencies
      #  - openssl-1.1 is required to install via pip from https sources
      #  - libffi7 is required to install Transcrypt
      yay -Sy --noconfirm --noeditmenu openssl-1.1 libffi7 python37
      # install JS bundler
      yay -Sy --noconfirm --noeditmenu rollup
      # install selenium helper and browser to run tests later
      yay -Sy --noconfirm --noeditmenu chromedriver google-chrome
  - setup_venv: |
      cd OOMAnalyser
      make venv
  - check_code_with_black: |
      cd OOMAnalyser
      make black-check
  - build: |
      cd OOMAnalyser
      make build
      ls -l OOMAnalyser.html OOMAnalyser.js
  - test: |
      cd OOMAnalyser
      make test
triggers:
  - action: email
    condition: failure
    to: Carsten Grohmann <mail@carstengrohmann.de>
