# Build file for OOMAnalyser
#
# Copyright (c) 2020-2022 Carsten Grohmann
# License: MIT (see LICENSE.txt)
# THIS PROGRAM COMES WITH NO WARRANTY

image: archlinux
arch:  x86_64
packages:
  - python3
  - python-virtualenv
  - git
  - xorg-server-xvfb
sources:
  - https://git.sr.ht/~carstengrohmann/OOMAnalyser
shell: null
tasks:
  - setup_pkgs: |
      yay -S --noconfirm --noeditmenu --noupgrademenu rollup chromedriver google-chrome
      git clone https://aur.archlinux.org/python37.git
      cd python37
      # disable optimizations to speedup build process by 8 minutes
      sed -i '/enable-optimizations/d' PKGBUILD
      makepkg --noconfirm -si --skippgpcheck
      cd ..
  - setup_venv: |
      cd OOMAnalyser
      make venv
  - build: |
      cd OOMAnalyser
      make build
      ls -l OOMAnalyser.html OOMAnalyser.js
  - webtest: |
      cd OOMAnalyser
      make test
triggers:
  - action: email
    condition: failure
    to: Carsten Grohmann <mail@carstengrohmann.de>
